import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutterapp2/presentation/pages/home_page.dart';
import 'package:flutterapp2/data/models/flower_address_model.dart';
import 'package:flutterapp2/presentation/utils/responsive_screen.dart';
import 'package:intl/intl.dart' as intl;
import 'package:provider/provider.dart';
import 'package:simple_autocomplete_formfield/simple_autocomplete_formfield.dart';
import 'package:flutterapp2/data/models/flower_name_model.dart';
import 'package:flutterapp2/data/models/user_location.dart';

class AddFlowerScreen extends StatefulWidget {
  @override
  _AddFlowerScreenState createState() => _AddFlowerScreenState();
}

class _AddFlowerScreenState extends State<AddFlowerScreen> {
  final _databaseReference = Firestore.instance;
  final _flowerName = <FlowerNameModel>[
    FlowerNameModel.name('ורד'),
    FlowerNameModel.name('אדר סורי'),
    FlowerNameModel.name('אוכם המדבר'),
    FlowerNameModel.name('אורן הצנובר'),
    FlowerNameModel.name('אילנתה בלוטית'),
    FlowerNameModel.name('אלה ארץ-ישראלית'),
    FlowerNameModel.name('אלון התבור'),
    FlowerNameModel.name('אלון מצוי'),
    FlowerNameModel.name('אמברוסיה צרת-עלים'),
    FlowerNameModel.name('אמברוסיה חשופת-שיבולת'),
    FlowerNameModel.name('אמברוסיה ימית'),
    FlowerNameModel.name('אמברוסיה מכונסת'),
    FlowerNameModel.name('אמברוסית גריי'),
    FlowerNameModel.name('אצבען מאדים'),
    FlowerNameModel.name('אשל היאור'),
    FlowerNameModel.name('אשל הירדן'),
    FlowerNameModel.name('אשל הפרקים'),
    FlowerNameModel.name('אשל מרובע'),
    FlowerNameModel.name('אשל קטן-פרחים'),
    FlowerNameModel.name('בוצין מפורץ'),
    FlowerNameModel.name('בוצין קיסריון'),
    FlowerNameModel.name('בוצין שיחני'),
    FlowerNameModel.name('בן-חיטה אריכא'),
    FlowerNameModel.name('בן-חיטה ביצני'),
    FlowerNameModel.name('בן-חיטה דל-שיבולת'),
    FlowerNameModel.name('בן-חיטה מדברי'),
    FlowerNameModel.name('בן-חיטה רב-אנפין'),
    FlowerNameModel.name('בן-חיטה שרוני'),
    FlowerNameModel.name('ברוש מצוי'),
    FlowerNameModel.name('בר-זית בינוני'),
    FlowerNameModel.name('גזיר המפרקים'),
    FlowerNameModel.name('גזר קיפח'),
    FlowerNameModel.name('דולב מזרחי'),
    FlowerNameModel.name('דורה תרבותית'),
    FlowerNameModel.name('דורת ארם-צובא'),
    FlowerNameModel.name('דמומית משוננת'),
    FlowerNameModel.name('הרדופנין נמוך'),
    FlowerNameModel.name('וושינגטוניה חסונה'),
    FlowerNameModel.name('ורבורגינת פקטורובסקי'),
    FlowerNameModel.name('זון אשון'),
    FlowerNameModel.name('זון מרצעני'),
    FlowerNameModel.name('זון רב-שנתי'),
    FlowerNameModel.name('זיפנוצה חבוי'),
    FlowerNameModel.name('זיפנוצה מדוקרן'),
    FlowerNameModel.name('זיף-נוצה ריסני'),
    FlowerNameModel.name('זית אירופי'),
    FlowerNameModel.name('זקניים משובלים'),
    FlowerNameModel.name('זקנן שעיר'),
    FlowerNameModel.name('חומעה ורודה'),
    FlowerNameModel.name('חומעה יפה'),
    FlowerNameModel.name('חומעה מגויידת'),
    FlowerNameModel.name('חומעה מסולסלת'),
    FlowerNameModel.name('חומעה משולחפת'),
    FlowerNameModel.name('חומעה משוננת'),
    FlowerNameModel.name('חפורית הפקעים'),
    FlowerNameModel.name('חפורית מוזרה'),
    FlowerNameModel.name('חפורית קטנה'),
    FlowerNameModel.name('חפורית קנרית'),
    FlowerNameModel.name('חרוב מצוי'),
    FlowerNameModel.name('חרצית דביקה'),
    FlowerNameModel.name('חרצית השדות'),
    FlowerNameModel.name('חרצית משוננת'),
    FlowerNameModel.name('חרצית עטורה'),
    FlowerNameModel.name('טיונית החולות'),
    FlowerNameModel.name('יבלית מצויה'),
    FlowerNameModel.name('ירבוז יווני'),
    FlowerNameModel.name('ירבוז הגדות'),
    FlowerNameModel.name('ירבוז לבן'),
    FlowerNameModel.name('ירבוז מבריק'),
    FlowerNameModel.name('ירבוז מופשל'),
    FlowerNameModel.name('ירבוז עדין'),
    FlowerNameModel.name('ירבוז פלמר'),
    FlowerNameModel.name('ירבוז שרוע'),
    FlowerNameModel.name('כף-אווז מבאישה'),
    FlowerNameModel.name('כף-אווז האשפות'),
    FlowerNameModel.name('כף-אווז הגינות'),
    FlowerNameModel.name('כף-אווז לבנה'),
    FlowerNameModel.name('כף-אווז רבת-עלים'),
    FlowerNameModel.name('כף-אווז ריחנית'),
    FlowerNameModel.name('כתלית זעירה'),
    FlowerNameModel.name('כתלית יהודה'),
    FlowerNameModel.name('כתלית פורטוגלית'),
    FlowerNameModel.name('לוף ירוק'),
    FlowerNameModel.name('לחך אזמלני'),
    FlowerNameModel.name('לחך בלוטי'),
    FlowerNameModel.name('לחך בשרני'),
    FlowerNameModel.name('לחך גדול'),
    FlowerNameModel.name('לחך גלילני'),
    FlowerNameModel.name('לחך הודי'),
    FlowerNameModel.name('לחך המלחות'),
    FlowerNameModel.name('לחך חום-לוע'),
    FlowerNameModel.name('לחך כרתי'),
    FlowerNameModel.name('לחך לופת'),
    FlowerNameModel.name('לחך מלבין'),
    FlowerNameModel.name('לחך מצוי'),
    FlowerNameModel.name('לחך סגלגל'),
    FlowerNameModel.name('לחך ריסני'),
    FlowerNameModel.name('לכיד הנחלים'),
    FlowerNameModel.name('לענה חד-זרעית'),
    FlowerNameModel.name('לענה שיחנית'),
    FlowerNameModel.name('לענת המדבר'),
    FlowerNameModel.name('מלוח מילר'),
    FlowerNameModel.name('מלוח קיפח'),
    FlowerNameModel.name('מלחית אשלגנית'),
    FlowerNameModel.name('מלחית הישימון'),
    FlowerNameModel.name('מלחית הערבה'),
    FlowerNameModel.name('מלחית קשקשנית'),
    FlowerNameModel.name('מרקולית מצויה'),
    FlowerNameModel.name('נשרן הדוחן'),
    FlowerNameModel.name('נשרן שעיר'),
    FlowerNameModel.name('סביון אביבי'),
    FlowerNameModel.name('סיסנית הבולבוסין'),
    FlowerNameModel.name('סיסנית הגינות'),
    FlowerNameModel.name('סיסנית חד-שנתית'),
    FlowerNameModel.name('סירה קוצנית'),
    FlowerNameModel.name('סמר מרצעני'),
    FlowerNameModel.name('סרפד הכדורים'),
    FlowerNameModel.name('סרפד צורב'),
    FlowerNameModel.name('סרפד קרומי'),
    FlowerNameModel.name('עדעד המדבר'),
    FlowerNameModel.name('ערבה לבנה'),
    FlowerNameModel.name('ערבה מחודדת'),
    FlowerNameModel.name('פיגם מצוי'),
    FlowerNameModel.name('פיקוס השיקמה'),
    FlowerNameModel.name('פלפלון דמוי-אלה'),
    FlowerNameModel.name('פספלון דו-טורי'),
    FlowerNameModel.name('פספלון מורחב'),
    FlowerNameModel.name('פרג אגסני'),
    FlowerNameModel.name('פרג זיפני'),
    FlowerNameModel.name('ציבורת ההרים'),
    FlowerNameModel.name('קזוארינה דקיקה'),
    FlowerNameModel.name('קיקיון מצוי'),
    FlowerNameModel.name('שיטה כחלחלה'),
    FlowerNameModel.name('שיטה סלילנית'),
    FlowerNameModel.name('שיטת המשוכות'),
    FlowerNameModel.name('שנית שוות שיניים'),
    FlowerNameModel.name('שקד מצוי'),
    FlowerNameModel.name('שרשר שיחני'),
    FlowerNameModel.name('תאנה'),
    FlowerNameModel.name('תות לבן'),
    FlowerNameModel.name('תות שחור'),
    FlowerNameModel.name('תמר מצוי'),
  ];
  final _flowerCity = <FlowerAddressModel>[
    FlowerAddressModel.address('אבו גווייעד'),
    FlowerAddressModel.address('אבו גוש'),
    FlowerAddressModel.address('אבו סנאן'),
    FlowerAddressModel.address('אבו סריחאן'),
    FlowerAddressModel.address('אבו עבדון'),
    FlowerAddressModel.address('אבו עמאר'),
    FlowerAddressModel.address('אבו עמרה'),
    FlowerAddressModel.address('אבו קורינאת'),
    FlowerAddressModel.address('אבו רובעייה'),
    FlowerAddressModel.address('אבו רוקייק'),
    FlowerAddressModel.address('אבו תלול'),
    FlowerAddressModel.address('אבטין'),
    FlowerAddressModel.address('אבטליון'),
    FlowerAddressModel.address('אביאל'),
    FlowerAddressModel.address('אביבים'),
    FlowerAddressModel.address('אביגדור'),
    FlowerAddressModel.address('אביחיל'),
    FlowerAddressModel.address('אביטל'),
    FlowerAddressModel.address('אביעזר'),
    FlowerAddressModel.address('אבירים'),
    FlowerAddressModel.address('אבן יהודה'),
    FlowerAddressModel.address('אבן מנחם'),
    FlowerAddressModel.address('אבן ספיר'),
    FlowerAddressModel.address('אבן שמואל'),
    FlowerAddressModel.address('אבני איתן'),
    FlowerAddressModel.address('אבני חפץ'),
    FlowerAddressModel.address('אבנת'),
    FlowerAddressModel.address('אבשלום'),
    FlowerAddressModel.address('אדורה'),
    FlowerAddressModel.address('אדירים'),
    FlowerAddressModel.address('אדמית'),
    FlowerAddressModel.address('אדרת'),
    FlowerAddressModel.address('אודים'),
    FlowerAddressModel.address('אודם'),
    FlowerAddressModel.address('אוהד'),
    FlowerAddressModel.address('אום אל-פחם'),
    FlowerAddressModel.address('אום אל-קוטוף'),
    FlowerAddressModel.address('אום בטין'),
    FlowerAddressModel.address('אומן'),
    FlowerAddressModel.address('אומץ'),
    FlowerAddressModel.address('אופקים'),
    FlowerAddressModel.address('אור הגנוז'),
    FlowerAddressModel.address('אור הנר'),
    FlowerAddressModel.address('אור יהודה'),
    FlowerAddressModel.address('אור עקיבא'),
    FlowerAddressModel.address('אורה'),
    FlowerAddressModel.address('אורון'),
    FlowerAddressModel.address('אורות'),
    FlowerAddressModel.address('אורטל'),
    FlowerAddressModel.address('אורים'),
    FlowerAddressModel.address('אורנים'),
    FlowerAddressModel.address('אורנית'),
    FlowerAddressModel.address('אושה'),
    FlowerAddressModel.address('אזור'),
    FlowerAddressModel.address('אילון'),
    FlowerAddressModel.address('אשדוד'),
    FlowerAddressModel.address('אשקלון'),
    FlowerAddressModel.address('באר שבע'),
    FlowerAddressModel.address('בשור'),
    FlowerAddressModel.address('גלילות'),
    FlowerAddressModel.address('גרר'),
    FlowerAddressModel.address('זכרון יעקב'),
    FlowerAddressModel.address('חדרה'),
    FlowerAddressModel.address('חולון'),
    FlowerAddressModel.address('חיפה'),
    FlowerAddressModel.address('חצור'),
    FlowerAddressModel.address('יחיעם'),
    FlowerAddressModel.address('ים המלח'),
    FlowerAddressModel.address('יקנעם'),
    FlowerAddressModel.address('כינרות'),
    FlowerAddressModel.address('כנרות'),
    FlowerAddressModel.address('כרמיאל'),
    FlowerAddressModel.address('לכיש'),
    FlowerAddressModel.address('מודיעין'),
    FlowerAddressModel.address('מלאכי'),
    FlowerAddressModel.address('נהרייה'),
    FlowerAddressModel.address('עכו'),
    FlowerAddressModel.address('פתח תקווה'),
    FlowerAddressModel.address('ראשל"צ'),
    FlowerAddressModel.address('רחובות'),
    FlowerAddressModel.address('רמלה'),
    FlowerAddressModel.address('רמת גן'),
    FlowerAddressModel.address('שפרעם'),
    FlowerAddressModel.address('תל אביב'),
    FlowerAddressModel.address('משגב'),
    FlowerAddressModel.address('אכסאל'),
    FlowerAddressModel.address('אכזיב'),
    FlowerAddressModel.address('אזור תעשייה נעמן(מילואות)'),
    FlowerAddressModel.address('אחווה'),
    FlowerAddressModel.address('אחוזם'),
    FlowerAddressModel.address('אחוזת ברק'),
    FlowerAddressModel.address('אחיהוד'),
    FlowerAddressModel.address('אחיטוב'),
    FlowerAddressModel.address('אחיסמך'),
    FlowerAddressModel.address('אחיעזר'),
    FlowerAddressModel.address('אטרש'),
    FlowerAddressModel.address('איבים'),
    FlowerAddressModel.address('אייל'),
    FlowerAddressModel.address('איילת השחר'),
    FlowerAddressModel.address('אילון'),
    FlowerAddressModel.address('אילון תבור'),
    FlowerAddressModel.address('אילות'),
    FlowerAddressModel.address('אילנייה'),
    FlowerAddressModel.address('אילת'),
    FlowerAddressModel.address('אירוס'),
    FlowerAddressModel.address('איתמר'),
    FlowerAddressModel.address('איתן'),
    FlowerAddressModel.address('איתנים'),
    FlowerAddressModel.address('אכסאל'),
    FlowerAddressModel.address('אל-עזי'),
    FlowerAddressModel.address('אל-עריאן'),
    FlowerAddressModel.address('אל-רום'),
    FlowerAddressModel.address('אח סייד'),
    FlowerAddressModel.address('אלומה'),
    FlowerAddressModel.address('אלומות'),
    FlowerAddressModel.address('אלון הגליל'),
    FlowerAddressModel.address('אלון מורה'),
    FlowerAddressModel.address('אלון שבות'),
    FlowerAddressModel.address('אלוני אבא'),
    FlowerAddressModel.address('אלוני הבשן'),
    FlowerAddressModel.address('אלוני יצחק'),
    FlowerAddressModel.address('אלונים'),
    FlowerAddressModel.address('אלי-עד'),
    FlowerAddressModel.address('אליאב'),
    FlowerAddressModel.address('אליכין'),
    FlowerAddressModel.address('אליפז'),
    FlowerAddressModel.address('אליפלט'),
    FlowerAddressModel.address('אליקים'),
    FlowerAddressModel.address('אלישיב'),
    FlowerAddressModel.address('אלישמע'),
    FlowerAddressModel.address('אלמגור'),
    FlowerAddressModel.address('אלמוג'),
    FlowerAddressModel.address('אלעד'),
    FlowerAddressModel.address('אלעזר'),
    FlowerAddressModel.address('אלפי מנשה'),
    FlowerAddressModel.address('אלקוש'),
    FlowerAddressModel.address('אלקנה'),
    FlowerAddressModel.address('אמונים'),
    FlowerAddressModel.address('אמירים'),
    FlowerAddressModel.address('אמנון'),
    FlowerAddressModel.address('אמציה'),
    FlowerAddressModel.address('אניעם'),
    FlowerAddressModel.address('אסד'),
    FlowerAddressModel.address('אספר'),
    FlowerAddressModel.address('אעבלין'),
    FlowerAddressModel.address('אעצם'),
    FlowerAddressModel.address('אפיניש'),
    FlowerAddressModel.address('אפיק'),
    FlowerAddressModel.address('אפיקים'),
    FlowerAddressModel.address('אפק'),
    FlowerAddressModel.address('אפרת'),
    FlowerAddressModel.address('ארבל'),
    FlowerAddressModel.address('ארגמן'),
    FlowerAddressModel.address('ארז'),
    FlowerAddressModel.address('אריאל'),
    FlowerAddressModel.address('ארסוף'),
    FlowerAddressModel.address('אשבול'),
    FlowerAddressModel.address('אשבל'),
    FlowerAddressModel.address('אשדוד'),
    FlowerAddressModel.address('אשדות יעקב(איחוד)'),
    FlowerAddressModel.address('אשדות יעקב(מאוחד)'),
    FlowerAddressModel.address('אשחר'),
    FlowerAddressModel.address('אשכולות'),
    FlowerAddressModel.address('אשל הנשיא'),
    FlowerAddressModel.address('אשלים'),
    FlowerAddressModel.address('אשקלון'),
    FlowerAddressModel.address('אשרת'),
    FlowerAddressModel.address('אשתאול'),
    FlowerAddressModel.address('באקה אל-גרביה'),
    FlowerAddressModel.address('באר אורה'),
    FlowerAddressModel.address('באר גנים'),
    FlowerAddressModel.address('באר טוביה'),
    FlowerAddressModel.address('באר יעקב'),
    FlowerAddressModel.address('באר מילכה'),
    FlowerAddressModel.address('באר שבע'),
    FlowerAddressModel.address('בארות יצחק'),
    FlowerAddressModel.address('בארותיים'),
    FlowerAddressModel.address('בארי'),
    FlowerAddressModel.address('בוסתן הגליל'),
    FlowerAddressModel.address('בועיינה-נוגידאת'),
    FlowerAddressModel.address('בוקעאתא'),
    FlowerAddressModel.address('בורגתה'),
    FlowerAddressModel.address('בחן'),
    FlowerAddressModel.address('בטחה'),
    FlowerAddressModel.address('מטה אשר'),
    FlowerAddressModel.address('ביצרון'),
    FlowerAddressModel.address('ביר אל-מכסור'),
    FlowerAddressModel.address('ביר הדאג'),
    FlowerAddressModel.address('בירייה'),
    FlowerAddressModel.address('בית אורן'),
    FlowerAddressModel.address('בית אל'),
    FlowerAddressModel.address('בית אלעזרי'),
    FlowerAddressModel.address('בית אלפא'),
    FlowerAddressModel.address('בית אריה'),
    FlowerAddressModel.address('בית ברל'),
    FlowerAddressModel.address('בית גן'),
    FlowerAddressModel.address('בית גוברין'),
    FlowerAddressModel.address('בית גמליאל'),
    FlowerAddressModel.address('בית דגן'),
    FlowerAddressModel.address('בית הגדי'),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address(''),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
  ];
  FlowerNameModel _flowerNameSelected;
  FlowerAddressModel _flowerAddressSelected;
  var _userLocation;

  @override
  Widget build(BuildContext context) {
    _userLocation = Provider.of<UserLocation>(context);//TAKE USER LOCATION
    return Scaffold(
      resizeToAvoidBottomPadding: false, // DO That the key don't up on search
      body: SafeArea(
        child: Container(
          decoration: BoxDecoration(
            image: DecorationImage(
                image: AssetImage("assets/back3.png"), fit: BoxFit.fill),
          ),
          child: Column(
            children: <Widget>[
              SizedBox(
                height: ResponsiveScreen().heightMediaQuery(context, 58),
              ),
              Container(
                margin: EdgeInsets.only(
                  left: ResponsiveScreen().widthMediaQuery(context, 20),
                  right: ResponsiveScreen().widthMediaQuery(context, 20),
                ),
                child: Directionality(
                  textDirection: TextDirection.rtl,
                  child: SimpleAutocompleteFormField<FlowerNameModel>(
                    decoration: InputDecoration(
                        border: OutlineInputBorder(
                          borderRadius: const BorderRadius.all(
                            const Radius.circular(30),
                          ),
                        ),
                        filled: true,
                        fillColor: Colors.white,
                        labelText: 'הכנס שם של צמח'),
                    suggestionsHeight:
                        ResponsiveScreen().heightMediaQuery(context, 160),
                    itemBuilder: (context, name) => Padding(
                      padding: EdgeInsets.all(8.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            name.name.toString(),
                            style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: Colors.black),
                          ),
                        ],
                      ),
                    ),
                    onSearch: (search) async => _flowerName
                        .where(
                          (name) => name.name.toLowerCase().contains(
                                search.toLowerCase(),
                              ),
                        )
                        .toList(),
                    itemFromString: (string) => _flowerName.singleWhere(
                        (name) =>
                            name.name.toLowerCase() == string.toLowerCase(),
                        orElse: () => null),
                    onChanged: (value) =>
                        setState(() => _flowerNameSelected = value),
                    onSaved: (value) =>
                        setState(() => _flowerNameSelected = value),
                    validator: (name) =>
                        name == null ? 'הצמח לא קיים' : null,
                  ),
                ),
              ),
              SizedBox(
                height: ResponsiveScreen().heightMediaQuery(context, 20),
              ),
              Container(
                margin: EdgeInsets.only(
                  left: ResponsiveScreen().widthMediaQuery(context, 20),
                  right: ResponsiveScreen().widthMediaQuery(context, 20),
                ),
                child: Directionality(
                  textDirection: TextDirection.rtl,
                  child: SimpleAutocompleteFormField<FlowerAddressModel>(
                    decoration: InputDecoration(
                        border: OutlineInputBorder(
                          borderRadius: const BorderRadius.all(
                            const Radius.circular(30),
                          ),
                        ),
                        filled: true,
                        fillColor: Colors.white,
                        labelText: 'הכנס שם של עיר'),
                    suggestionsHeight:
                        ResponsiveScreen().heightMediaQuery(context, 160),
                    itemBuilder: (context, address) => Padding(
                      padding: EdgeInsets.all(8.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            address.address.toString(),
                            style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: Colors.black),
                          ),
                        ],
                      ),
                    ),
                    onSearch: (search) async => _flowerCity
                        .where(
                          (address) => address.address.toLowerCase().contains(
                                search.toLowerCase(),
                              ),
                        )
                        .toList(),
                    itemFromString: (string) => _flowerCity.singleWhere(
                        (address) =>
                            address.address.toLowerCase() ==
                            string.toLowerCase(),
                        orElse: () => null),
                    onChanged: (value) =>
                        setState(() => _flowerAddressSelected = value),
                    onSaved: (value) =>
                        setState(() => _flowerAddressSelected = value),
                    validator: (address) =>
                        address == null ? 'העיר לא קיימת' : null,
                  ),
                ),
              ),
              SizedBox(
                height: ResponsiveScreen().heightMediaQuery(context, 20),
              ),
              RaisedButton(
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(80.0),
                ),
                onPressed: () => {//check if one of field empty will jump error message to user
                  _btnPress(
                      _flowerAddressSelected != null
                          ? _flowerAddressSelected.address
                          : '',
                      _flowerNameSelected != null
                          ? _flowerNameSelected.name
                          : '')
                },
                padding: EdgeInsets.all(0.0),
                child: Ink(
                  decoration: const BoxDecoration(
                    gradient: LinearGradient(
                      colors: <Color>[
                        Colors.blueGrey,
                        Colors.green,
                      ],
                    ),
                    borderRadius: BorderRadius.all(
                      Radius.circular(80.0),
                    ),
                  ),
                  child: Container(
                    constraints: BoxConstraints(
                      minWidth:
                          ResponsiveScreen().widthMediaQuery(context, 150),//propration to screen
                      minHeight:
                          ResponsiveScreen().heightMediaQuery(context, 45),
                    ),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: <Widget>[
                        Text(
                          'הוסף צמח',
                          style: TextStyle(color: Colors.white),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Future _btnPress(String city, String name) async {
    if (city == '' || name == '') {
      showDialog(
        context: context,
        builder: (_) => AlertDialog(
          backgroundColor: Color(0xFFFDF2E9),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Icon(
                Icons.error,
                color: Colors.red,
                size: 50,
              ),
              SizedBox(
                height: 6.5,
              ),
              Center(
                child: Text(
                  "אחד הפרטים או יותר חסר נא הוסף",
                  style: TextStyle(fontWeight: FontWeight.bold),
                  textAlign: TextAlign.center,
                ),
              ),
              SizedBox(
                height: 6.5,
              ),
              Container(
                width: double.infinity,
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(40),
                  child: RaisedButton(
                    color: Colors.blueAccent,
                    onPressed: () {
                      Navigator.pop(context);
                    },
                    child: Text(
                      "תודה",
                      style: TextStyle(color: Colors.white, fontSize: 25),
                    ),
                  ),
                ),
              )
            ],
          ),
        ),
      );
    } else {
      var now = DateTime.now();
      String formattedDate = intl.DateFormat('MM').format(now);
      int myMonth = int.parse(formattedDate);

      String id = city + name; // id for compare

      int count;

      var document = _databaseReference.collection(city).document(id);
      document.get().then(
        (document) {
          setState(
            () {
              if (document.exists) {
                count = document['count'];
              }
            },
          );
        },
      ).then(
        (value) async =>
            await _databaseReference.collection(city).document(id).setData(
          {
            "date": myMonth,
            "name": name,
            "count": count != null ? count + 1 : 1,
            "latitude": _userLocation.latitude,
            "longitude": _userLocation.longitude,
          },
        ).then(
          (value) => {
            showDialog(
              context: context,
              builder: (_) => AlertDialog(
                backgroundColor: Color(0xFFFDF2E9),
                content: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    Icon(
                      Icons.check_circle,
                      color: Colors.green,
                      size: 50,
                    ),
                    SizedBox(
                      height: 6.5,
                    ),
                    Center(
                      child: Text(
                        " הדיווח עבר בהצלחה\nהמערכת מבצעת בדיקה",
                        style: TextStyle(fontWeight: FontWeight.bold),
                        textAlign: TextAlign.center,
                      ),
                    ),
                    SizedBox(
                      height: 6.5,
                    ),
                    Container(
                      width: double.infinity,
                      child: ClipRRect(
                        borderRadius: BorderRadius.circular(40),
                        child: RaisedButton(
                          color: Colors.blueAccent,
                          onPressed: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (context) => HomePage(),
                              ),
                            );
                          },
                          child: Text(
                            "בכיף",
                            style: TextStyle(color: Colors.white, fontSize: 25),
                          ),
                        ),
                      ),
                    )
                  ],
                ),
              ),
            )
          },
        ),
      );
    }
  }
}
