import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutterapp2/presentation/pages/home_page.dart';
import 'package:flutterapp2/data/models/flower_address_model.dart';
import 'package:flutterapp2/presentation/utils/responsive_screen.dart';
import 'package:intl/intl.dart' as intl;
import 'package:provider/provider.dart';
import 'package:simple_autocomplete_formfield/simple_autocomplete_formfield.dart';
import 'package:flutterapp2/data/models/flower_name_model.dart';
import 'package:flutterapp2/data/models/user_location.dart';

class AddFlowerScreen extends StatefulWidget {
  @override
  _AddFlowerScreenState createState() => _AddFlowerScreenState();
}

class _AddFlowerScreenState extends State<AddFlowerScreen> {
  final _databaseReference = Firestore.instance;
  final _flowerName = <FlowerNameModel>[
    FlowerNameModel.name('ורד'),
    FlowerNameModel.name('אדר סורי'),
    FlowerNameModel.name('אוכם המדבר'),
    FlowerNameModel.name('אורן הצנובר'),
    FlowerNameModel.name('אילנתה בלוטית'),
    FlowerNameModel.name('אלה ארץ-ישראלית'),
    FlowerNameModel.name('אלון התבור'),
    FlowerNameModel.name('אלון מצוי'),
    FlowerNameModel.name('אמברוסיה צרת-עלים'),
    FlowerNameModel.name('אמברוסיה חשופת-שיבולת'),
    FlowerNameModel.name('אמברוסיה ימית'),
    FlowerNameModel.name('אמברוסיה מכונסת'),
    FlowerNameModel.name('אמברוסית גריי'),
    FlowerNameModel.name('אצבען מאדים'),
    FlowerNameModel.name('אשל היאור'),
    FlowerNameModel.name('אשל הירדן'),
    FlowerNameModel.name('אשל הפרקים'),
    FlowerNameModel.name('אשל מרובע'),
    FlowerNameModel.name('אשל קטן-פרחים'),
    FlowerNameModel.name('בוצין מפורץ'),
    FlowerNameModel.name('בוצין קיסריון'),
    FlowerNameModel.name('בוצין שיחני'),
    FlowerNameModel.name('בן-חיטה אריכא'),
    FlowerNameModel.name('בן-חיטה ביצני'),
    FlowerNameModel.name('בן-חיטה דל-שיבולת'),
    FlowerNameModel.name('בן-חיטה מדברי'),
    FlowerNameModel.name('בן-חיטה רב-אנפין'),
    FlowerNameModel.name('בן-חיטה שרוני'),
    FlowerNameModel.name('ברוש מצוי'),
    FlowerNameModel.name('בר-זית בינוני'),
    FlowerNameModel.name('גזיר המפרקים'),
    FlowerNameModel.name('גזר קיפח'),
    FlowerNameModel.name('דולב מזרחי'),
    FlowerNameModel.name('דורה תרבותית'),
    FlowerNameModel.name('דורת ארם-צובא'),
    FlowerNameModel.name('דמומית משוננת'),
    FlowerNameModel.name('הרדופנין נמוך'),
    FlowerNameModel.name('וושינגטוניה חסונה'),
    FlowerNameModel.name('ורבורגינת פקטורובסקי'),
    FlowerNameModel.name('זון אשון'),
    FlowerNameModel.name('זון מרצעני'),
    FlowerNameModel.name('זון רב-שנתי'),
    FlowerNameModel.name('זיפנוצה חבוי'),
    FlowerNameModel.name('זיפנוצה מדוקרן'),
    FlowerNameModel.name('זיף-נוצה ריסני'),
    FlowerNameModel.name('זית אירופי'),
    FlowerNameModel.name('זקניים משובלים'),
    FlowerNameModel.name('זקנן שעיר'),
    FlowerNameModel.name('חומעה ורודה'),
    FlowerNameModel.name('חומעה יפה'),
    FlowerNameModel.name('חומעה מגויידת'),
    FlowerNameModel.name('חומעה מסולסלת'),
    FlowerNameModel.name('חומעה משולחפת'),
    FlowerNameModel.name('חומעה משוננת'),
    FlowerNameModel.name('חפורית הפקעים'),
    FlowerNameModel.name('חפורית מוזרה'),
    FlowerNameModel.name('חפורית קטנה'),
    FlowerNameModel.name('חפורית קנרית'),
    FlowerNameModel.name('חרוב מצוי'),
    FlowerNameModel.name('חרצית דביקה'),
    FlowerNameModel.name('חרצית השדות'),
    FlowerNameModel.name('חרצית משוננת'),
    FlowerNameModel.name('חרצית עטורה'),
    FlowerNameModel.name('טיונית החולות'),
    FlowerNameModel.name('יבלית מצויה'),
    FlowerNameModel.name('ירבוז יווני'),
    FlowerNameModel.name('ירבוז הגדות'),
    FlowerNameModel.name('ירבוז לבן'),
    FlowerNameModel.name('ירבוז מבריק'),
    FlowerNameModel.name('ירבוז מופשל'),
    FlowerNameModel.name('ירבוז עדין'),
    FlowerNameModel.name('ירבוז פלמר'),
    FlowerNameModel.name('ירבוז שרוע'),
    FlowerNameModel.name('כף-אווז מבאישה'),
    FlowerNameModel.name('כף-אווז האשפות'),
    FlowerNameModel.name('כף-אווז הגינות'),
    FlowerNameModel.name('כף-אווז לבנה'),
    FlowerNameModel.name('כף-אווז רבת-עלים'),
    FlowerNameModel.name('כף-אווז ריחנית'),
    FlowerNameModel.name('כתלית זעירה'),
    FlowerNameModel.name('כתלית יהודה'),
    FlowerNameModel.name('כתלית פורטוגלית'),
    FlowerNameModel.name('לוף ירוק'),
    FlowerNameModel.name('לחך אזמלני'),
    FlowerNameModel.name('לחך בלוטי'),
    FlowerNameModel.name('לחך בשרני'),
    FlowerNameModel.name('לחך גדול'),
    FlowerNameModel.name('לחך גלילני'),
    FlowerNameModel.name('לחך הודי'),
    FlowerNameModel.name('לחך המלחות'),
    FlowerNameModel.name('לחך חום-לוע'),
    FlowerNameModel.name('לחך כרתי'),
    FlowerNameModel.name('לחך לופת'),
    FlowerNameModel.name('לחך מלבין'),
    FlowerNameModel.name('לחך מצוי'),
    FlowerNameModel.name('לחך סגלגל'),
    FlowerNameModel.name('לחך ריסני'),
    FlowerNameModel.name('לכיד הנחלים'),
    FlowerNameModel.name('לענה חד-זרעית'),
    FlowerNameModel.name('לענה שיחנית'),
    FlowerNameModel.name('לענת המדבר'),
    FlowerNameModel.name('מלוח מילר'),
    FlowerNameModel.name('מלוח קיפח'),
    FlowerNameModel.name('מלחית אשלגנית'),
    FlowerNameModel.name('מלחית הישימון'),
    FlowerNameModel.name('מלחית הערבה'),
    FlowerNameModel.name('מלחית קשקשנית'),
    FlowerNameModel.name('מרקולית מצויה'),
    FlowerNameModel.name('נשרן הדוחן'),
    FlowerNameModel.name('נשרן שעיר'),
    FlowerNameModel.name('סביון אביבי'),
    FlowerNameModel.name('סיסנית הבולבוסין'),
    FlowerNameModel.name('סיסנית הגינות'),
    FlowerNameModel.name('סיסנית חד-שנתית'),
    FlowerNameModel.name('סירה קוצנית'),
    FlowerNameModel.name('סמר מרצעני'),
    FlowerNameModel.name('סרפד הכדורים'),
    FlowerNameModel.name('סרפד צורב'),
    FlowerNameModel.name('סרפד קרומי'),
    FlowerNameModel.name('עדעד המדבר'),
    FlowerNameModel.name('ערבה לבנה'),
    FlowerNameModel.name('ערבה מחודדת'),
    FlowerNameModel.name('פיגם מצוי'),
    FlowerNameModel.name('פיקוס השיקמה'),
    FlowerNameModel.name('פלפלון דמוי-אלה'),
    FlowerNameModel.name('פספלון דו-טורי'),
    FlowerNameModel.name('פספלון מורחב'),
    FlowerNameModel.name('פרג אגסני'),
    FlowerNameModel.name('פרג זיפני'),
    FlowerNameModel.name('ציבורת ההרים'),
    FlowerNameModel.name('קזוארינה דקיקה'),
    FlowerNameModel.name('קיקיון מצוי'),
    FlowerNameModel.name('שיטה כחלחלה'),
    FlowerNameModel.name('שיטה סלילנית'),
    FlowerNameModel.name('שיטת המשוכות'),
    FlowerNameModel.name('שנית שוות שיניים'),
    FlowerNameModel.name('שקד מצוי'),
    FlowerNameModel.name('שרשר שיחני'),
    FlowerNameModel.name('תאנה'),
    FlowerNameModel.name('תות לבן'),
    FlowerNameModel.name('תות שחור'),
    FlowerNameModel.name('תמר מצוי'),
  ];
  final _flowerCity = <FlowerAddressModel>[
    FlowerAddressModel.address('אבו גווייעד'),
    FlowerAddressModel.address('אבו גוש'),
    FlowerAddressModel.address('אבו סנאן'),
    FlowerAddressModel.address('אבו סריחאן'),
    FlowerAddressModel.address('אבו עבדון'),
    FlowerAddressModel.address('אבו עמאר'),
    FlowerAddressModel.address('אבו עמרה'),
    FlowerAddressModel.address('אבו קורינאת'),
    FlowerAddressModel.address('אבו רובעייה'),
    FlowerAddressModel.address('אבו רוקייק'),
    FlowerAddressModel.address('אבו תלול'),
    FlowerAddressModel.address('אבטין'),
    FlowerAddressModel.address('אבטליון'),
    FlowerAddressModel.address('אביאל'),
    FlowerAddressModel.address('אביבים'),
    FlowerAddressModel.address('אביגדור'),
    FlowerAddressModel.address('אביחיל'),
    FlowerAddressModel.address('אביטל'),
    FlowerAddressModel.address('אביעזר'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('נתניה'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
    FlowerAddressModel.address('ירושלים'),
  ];
  FlowerNameModel _flowerNameSelected;
  FlowerAddressModel _flowerAddressSelected;
  var _userLocation;

  @override
  Widget build(BuildContext context) {
    _userLocation = Provider.of<UserLocation>(context);//TAKE USER LOCATION
    return Scaffold(
      resizeToAvoidBottomPadding: false, // DO That the key don't up on search
      body: SafeArea(
        child: Container(
          decoration: BoxDecoration(
            image: DecorationImage(
                image: AssetImage("assets/back3.png"), fit: BoxFit.fill),
          ),
          child: Column(
            children: <Widget>[
              SizedBox(
                height: ResponsiveScreen().heightMediaQuery(context, 58),
              ),
              Container(
                margin: EdgeInsets.only(
                  left: ResponsiveScreen().widthMediaQuery(context, 20),
                  right: ResponsiveScreen().widthMediaQuery(context, 20),
                ),
                child: Directionality(
                  textDirection: TextDirection.rtl,
                  child: SimpleAutocompleteFormField<FlowerNameModel>(
                    decoration: InputDecoration(
                        border: OutlineInputBorder(
                          borderRadius: const BorderRadius.all(
                            const Radius.circular(30),
                          ),
                        ),
                        filled: true,
                        fillColor: Colors.white,
                        labelText: 'הכנס שם של צמח'),
                    suggestionsHeight:
                        ResponsiveScreen().heightMediaQuery(context, 160),
                    itemBuilder: (context, name) => Padding(
                      padding: EdgeInsets.all(8.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            name.name.toString(),
                            style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: Colors.black),
                          ),
                        ],
                      ),
                    ),
                    onSearch: (search) async => _flowerName
                        .where(
                          (name) => name.name.toLowerCase().contains(
                                search.toLowerCase(),
                              ),
                        )
                        .toList(),
                    itemFromString: (string) => _flowerName.singleWhere(
                        (name) =>
                            name.name.toLowerCase() == string.toLowerCase(),
                        orElse: () => null),
                    onChanged: (value) =>
                        setState(() => _flowerNameSelected = value),
                    onSaved: (value) =>
                        setState(() => _flowerNameSelected = value),
                    validator: (name) =>
                        name == null ? 'הצמח לא קיים' : null,
                  ),
                ),
              ),
              SizedBox(
                height: ResponsiveScreen().heightMediaQuery(context, 20),
              ),
              Container(
                margin: EdgeInsets.only(
                  left: ResponsiveScreen().widthMediaQuery(context, 20),
                  right: ResponsiveScreen().widthMediaQuery(context, 20),
                ),
                child: Directionality(
                  textDirection: TextDirection.rtl,
                  child: SimpleAutocompleteFormField<FlowerAddressModel>(
                    decoration: InputDecoration(
                        border: OutlineInputBorder(
                          borderRadius: const BorderRadius.all(
                            const Radius.circular(30),
                          ),
                        ),
                        filled: true,
                        fillColor: Colors.white,
                        labelText: 'הכנס שם של עיר'),
                    suggestionsHeight:
                        ResponsiveScreen().heightMediaQuery(context, 160),
                    itemBuilder: (context, address) => Padding(
                      padding: EdgeInsets.all(8.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            address.address.toString(),
                            style: TextStyle(
                                fontWeight: FontWeight.bold,
                                color: Colors.black),
                          ),
                        ],
                      ),
                    ),
                    onSearch: (search) async => _flowerCity
                        .where(
                          (address) => address.address.toLowerCase().contains(
                                search.toLowerCase(),
                              ),
                        )
                        .toList(),
                    itemFromString: (string) => _flowerCity.singleWhere(
                        (address) =>
                            address.address.toLowerCase() ==
                            string.toLowerCase(),
                        orElse: () => null),
                    onChanged: (value) =>
                        setState(() => _flowerAddressSelected = value),
                    onSaved: (value) =>
                        setState(() => _flowerAddressSelected = value),
                    validator: (address) =>
                        address == null ? 'העיר לא קיימת' : null,
                  ),
                ),
              ),
              SizedBox(
                height: ResponsiveScreen().heightMediaQuery(context, 20),
              ),
              RaisedButton(
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(80.0),
                ),
                onPressed: () => {//check if one of field empty will jump error message to user
                  _btnPress(
                      _flowerAddressSelected != null
                          ? _flowerAddressSelected.address
                          : '',
                      _flowerNameSelected != null
                          ? _flowerNameSelected.name
                          : '')
                },
                padding: EdgeInsets.all(0.0),
                child: Ink(
                  decoration: const BoxDecoration(
                    gradient: LinearGradient(
                      colors: <Color>[
                        Colors.blueGrey,
                        Colors.green,
                      ],
                    ),
                    borderRadius: BorderRadius.all(
                      Radius.circular(80.0),
                    ),
                  ),
                  child: Container(
                    constraints: BoxConstraints(
                      minWidth:
                          ResponsiveScreen().widthMediaQuery(context, 150),//propration to screen
                      minHeight:
                          ResponsiveScreen().heightMediaQuery(context, 45),
                    ),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: <Widget>[
                        Text(
                          'הוסף צמח',
                          style: TextStyle(color: Colors.white),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Future _btnPress(String city, String name) async {
    if (city == '' || name == '') {
      showDialog(
        context: context,
        builder: (_) => AlertDialog(
          backgroundColor: Color(0xFFFDF2E9),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Icon(
                Icons.error,
                color: Colors.red,
                size: 50,
              ),
              SizedBox(
                height: 6.5,
              ),
              Center(
                child: Text(
                  "אחד הפרטים חסר נא הוסף",
                  style: TextStyle(fontWeight: FontWeight.bold),
                  textAlign: TextAlign.center,
                ),
              ),
              SizedBox(
                height: 6.5,
              ),
              Container(
                width: double.infinity,
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(40),
                  child: RaisedButton(
                    color: Colors.blueAccent,
                    onPressed: () {
                      Navigator.pop(context);
                    },
                    child: Text(
                      "תודה",
                      style: TextStyle(color: Colors.white, fontSize: 25),
                    ),
                  ),
                ),
              )
            ],
          ),
        ),
      );
    } else {
      var now = DateTime.now();
      String formattedDate = intl.DateFormat('MM').format(now);
      int myMonth = int.parse(formattedDate);

      String id = city + name; // id for compare

      int count;

      var document = _databaseReference.collection(city).document(id);
      document.get().then(
        (document) {
          setState(
            () {
              if (document.exists) {
                count = document['count'];
              }
            },
          );
        },
      ).then(
        (value) async =>
            await _databaseReference.collection(city).document(id).setData(
          {
            "date": myMonth,
            "name": name,
            "count": count != null ? count + 1 : 1,
            "latitude": _userLocation.latitude,
            "longitude": _userLocation.longitude,
          },
        ).then(
          (value) => {
            showDialog(
              context: context,
              builder: (_) => AlertDialog(
                backgroundColor: Color(0xFFFDF2E9),
                content: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    Icon(
                      Icons.check_circle,
                      color: Colors.green,
                      size: 50,
                    ),
                    SizedBox(
                      height: 6.5,
                    ),
                    Center(
                      child: Text(
                        "הדיווח עבר בהצלחה\nהמערכת מבצעת בדיקה",
                        style: TextStyle(fontWeight: FontWeight.bold),
                        textAlign: TextAlign.center,
                      ),
                    ),
                    SizedBox(
                      height: 6.5,
                    ),
                    Container(
                      width: double.infinity,
                      child: ClipRRect(
                        borderRadius: BorderRadius.circular(40),
                        child: RaisedButton(
                          color: Colors.blueAccent,
                          onPressed: () {
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (context) => HomePage(),
                              ),
                            );
                          },
                          child: Text(
                            "בכיף",
                            style: TextStyle(color: Colors.white, fontSize: 25),
                          ),
                        ),
                      ),
                    )
                  ],
                ),
              ),
            )
          },
        ),
      );
    }
  }
}
